version: "3.8"

services:
  fastapi:
    image: fastapi_multi
    build: .
    container_name: fastapi_single
    ports:
      - "8050:8000"
    volumes:
      - .:/app
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]